export interface Doctor {
  id: string;
  name: string;
  nameBn: string;
  specialty: string;
  specialtyBn: string;
  department: string;
  hospital: string;
  hospitalBn: string;
  location: string;
  locationBn: string;
  fee: number;
  phone: string;
  available: string;
  availableBn: string;
  rating: number;
  experience: string;
  experienceBn: string;
  chamberTime: string;
  chamberTimeBn: string;
  image: string;
}

export const doctors: Doctor[] = [
  // Cardiology
  {
    id: "d1",
    name: "Prof. Dr. Md. Harisul Hoque",
    nameBn: "প্রফেসর ডা. মো. হারিসুল হক",
    specialty: "Interventional Cardiology",
    specialtyBn: "ইন্টারভেনশনাল কার্ডিওলজি",
    department: "cardiology",
    hospital: "Bangabandhu Sheikh Mujib Medical University (BSMMU)",
    hospitalBn: "বঙ্গবন্ধু শেখ মুজিব মেডিকেল বিশ্ববিদ্যালয়",
    location: "Shahbag, Dhaka",
    locationBn: "শাহবাগ, ঢাকা",
    fee: 1500,
    phone: "+880-2-9661051",
    available: "Sun, Tue, Thu",
    availableBn: "রবি, মঙ্গল, বৃহঃ",
    rating: 4.8,
    experience: "25+ years",
    experienceBn: "২৫+ বছর",
    chamberTime: "5:00 PM - 9:00 PM",
    chamberTimeBn: "বিকাল ৫:০০ - রাত ৯:০০",
    image: "/doctors/cardio1.jpg",
  },
  {
    id: "d2",
    name: "Dr. Sajal Krishna Banerjee",
    nameBn: "ডা. সজল কৃষ্ণ ব্যানার্জী",
    specialty: "Clinical Cardiology",
    specialtyBn: "ক্লিনিক্যাল কার্ডিওলজি",
    department: "cardiology",
    hospital: "National Heart Foundation",
    hospitalBn: "জাতীয় হৃদরোগ ইনস্টিটিউট",
    location: "Mirpur, Dhaka",
    locationBn: "মিরপুর, ঢাকা",
    fee: 1200,
    phone: "+880-2-9116551",
    available: "Sat, Mon, Wed",
    availableBn: "শনি, সোম, বুধ",
    rating: 4.7,
    experience: "20+ years",
    experienceBn: "২০+ বছর",
    chamberTime: "4:00 PM - 8:00 PM",
    chamberTimeBn: "বিকাল ৪:০০ - রাত ৮:০০",
    image: "/doctors/cardio2.jpg",
  },
  // Neurology
  {
    id: "d3",
    name: "Prof. Dr. Quazi Deen Mohammad",
    nameBn: "প্রফেসর ডা. কাজী দীন মোহাম্মদ",
    specialty: "Neurology & Stroke Medicine",
    specialtyBn: "নিউরোলজি ও স্ট্রোক মেডিসিন",
    department: "neurology",
    hospital: "National Institute of Neurosciences (NINS)",
    hospitalBn: "জাতীয় নিউরোসায়েন্সেস ইনস্টিটিউট",
    location: "Agargaon, Dhaka",
    locationBn: "আগারগাঁও, ঢাকা",
    fee: 1500,
    phone: "+880-2-8431947",
    available: "Sun, Tue, Thu",
    availableBn: "রবি, মঙ্গল, বৃহঃ",
    rating: 4.9,
    experience: "30+ years",
    experienceBn: "৩০+ বছর",
    chamberTime: "6:00 PM - 9:00 PM",
    chamberTimeBn: "সন্ধ্যা ৬:০০ - রাত ৯:০০",
    image: "/doctors/neuro1.jpg",
  },
  {
    id: "d4",
    name: "Dr. Md. Azharul Hoque",
    nameBn: "ডা. মো. আজহারুল হক",
    specialty: "Epilepsy & Movement Disorders",
    specialtyBn: "মৃগী ও মুভমেন্ট ডিসঅর্ডার",
    department: "neurology",
    hospital: "Dhaka Medical College Hospital",
    hospitalBn: "ঢাকা মেডিকেল কলেজ হাসপাতাল",
    location: "Secretariat, Dhaka",
    locationBn: "সচিবালয়, ঢাকা",
    fee: 1000,
    phone: "+880-2-55165088",
    available: "Sat, Mon, Wed",
    availableBn: "শনি, সোম, বুধ",
    rating: 4.6,
    experience: "18+ years",
    experienceBn: "১৮+ বছর",
    chamberTime: "5:00 PM - 8:00 PM",
    chamberTimeBn: "বিকাল ৫:০০ - রাত ৮:০০",
    image: "/doctors/neuro2.jpg",
  },
  // Orthopedics
  {
    id: "d5",
    name: "Prof. Dr. Md. Shahiduzzaman",
    nameBn: "প্রফেসর ডা. মো. শহীদুজ্জামান",
    specialty: "Joint Replacement & Sports Injury",
    specialtyBn: "জয়েন্ট রিপ্লেসমেন্ট ও স্পোর্টস ইনজুরি",
    department: "orthopedics",
    hospital: "NITOR (National Institute of Traumatology)",
    hospitalBn: "জাতীয় অর্থোপেডিক হাসপাতাল (নিটোর)",
    location: "Sher-e-Bangla Nagar, Dhaka",
    locationBn: "শের-এ-বাংলা নগর, ঢাকা",
    fee: 1200,
    phone: "+880-2-9116876",
    available: "Sun, Tue, Thu",
    availableBn: "রবি, মঙ্গল, বৃহঃ",
    rating: 4.7,
    experience: "22+ years",
    experienceBn: "২২+ বছর",
    chamberTime: "4:00 PM - 8:00 PM",
    chamberTimeBn: "বিকাল ৪:০০ - রাত ৮:০০",
    image: "/doctors/ortho1.jpg",
  },
  // Dermatology
  {
    id: "d6",
    name: "Dr. Rashida Akhter",
    nameBn: "ডা. রশিদা আখতার",
    specialty: "Dermatology & Venereology",
    specialtyBn: "চর্ম ও যৌনরোগ বিদ্যা",
    department: "dermatology",
    hospital: "Lab Aid Specialized Hospital",
    hospitalBn: "ল্যাব এইড স্পেশালাইজড হাসপাতাল",
    location: "Dhanmondi, Dhaka",
    locationBn: "ধানমন্ডি, ঢাকা",
    fee: 1000,
    phone: "+880-2-9612345",
    available: "Sat, Mon, Wed, Fri",
    availableBn: "শনি, সোম, বুধ, শুক্র",
    rating: 4.5,
    experience: "15+ years",
    experienceBn: "১৫+ বছর",
    chamberTime: "3:00 PM - 7:00 PM",
    chamberTimeBn: "বিকাল ৩:০০ - সন্ধ্যা ৭:০০",
    image: "/doctors/derm1.jpg",
  },
  // Gastroenterology
  {
    id: "d7",
    name: "Prof. Dr. Md. Fazal Karim",
    nameBn: "প্রফেসর ডা. মো. ফজল করিম",
    specialty: "Hepatology & Gastroenterology",
    specialtyBn: "হেপাটোলজি ও গ্যাস্ট্রোএন্টারোলজি",
    department: "gastroenterology",
    hospital: "Bangabandhu Sheikh Mujib Medical University",
    hospitalBn: "বঙ্গবন্ধু শেখ মুজিব মেডিকেল বিশ্ববিদ্যালয়",
    location: "Shahbag, Dhaka",
    locationBn: "শাহবাগ, ঢাকা",
    fee: 1500,
    phone: "+880-2-9661064",
    available: "Sun, Tue, Thu",
    availableBn: "রবি, মঙ্গল, বৃহঃ",
    rating: 4.8,
    experience: "28+ years",
    experienceBn: "২৮+ বছর",
    chamberTime: "5:00 PM - 9:00 PM",
    chamberTimeBn: "বিকাল ৫:০০ - রাত ৯:০০",
    image: "/doctors/gastro1.jpg",
  },
  // ENT
  {
    id: "d8",
    name: "Dr. Nasima Akhter",
    nameBn: "ডা. নাসিমা আখতার",
    specialty: "ENT & Head-Neck Surgery",
    specialtyBn: "নাক-কান-গলা ও হেড-নেক সার্জারি",
    department: "ent",
    hospital: "Square Hospital",
    hospitalBn: "স্কয়ার হাসপাতাল",
    location: "Panthapath, Dhaka",
    locationBn: "পান্থপথ, ঢাকা",
    fee: 2000,
    phone: "+880-2-8159457",
    available: "Sat, Mon, Wed",
    availableBn: "শনি, সোম, বুধ",
    rating: 4.6,
    experience: "16+ years",
    experienceBn: "১৬+ বছর",
    chamberTime: "4:00 PM - 8:00 PM",
    chamberTimeBn: "বিকাল ৪:০০ - রাত ৮:০০",
    image: "/doctors/ent1.jpg",
  },
  // Pulmonology
  {
    id: "d9",
    name: "Prof. Dr. Md. Mostafizur Rahman",
    nameBn: "প্রফেসর ডা. মো. মোস্তাফিজুর রহমান",
    specialty: "Pulmonology & Respiratory Medicine",
    specialtyBn: "পালমোনোলজি ও শ্বাসতন্ত্র মেডিসিন",
    department: "pulmonology",
    hospital: "National Institute of Diseases of the Chest and Hospital (NIDCH)",
    hospitalBn: "জাতীয় বক্ষব্যাধি ইনস্টিটিউট ও হাসপাতাল",
    location: "Mohakhali, Dhaka",
    locationBn: "মহাখালী, ঢাকা",
    fee: 1000,
    phone: "+880-2-9898989",
    available: "Sun, Tue, Thu",
    availableBn: "রবি, মঙ্গল, বৃহঃ",
    rating: 4.7,
    experience: "24+ years",
    experienceBn: "২৪+ বছর",
    chamberTime: "5:00 PM - 8:00 PM",
    chamberTimeBn: "বিকাল ৫:০০ - রাত ৮:০০",
    image: "/doctors/pulmo1.jpg",
  },
  // General Medicine / Internal Medicine
  {
    id: "d10",
    name: "Dr. Farhana Rahman",
    nameBn: "ডা. ফারহানা রহমান",
    specialty: "Internal Medicine & Diabetes",
    specialtyBn: "ইন্টারনাল মেডিসিন ও ডায়াবেটিস",
    department: "general_medicine",
    hospital: "BIRDEM General Hospital",
    hospitalBn: "বারডেম জেনারেল হাসপাতাল",
    location: "Shahbag, Dhaka",
    locationBn: "শাহবাগ, ঢাকা",
    fee: 800,
    phone: "+880-2-9661551",
    available: "Sat-Thu",
    availableBn: "শনি-বৃহঃ",
    rating: 4.5,
    experience: "12+ years",
    experienceBn: "১২+ বছর",
    chamberTime: "9:00 AM - 1:00 PM",
    chamberTimeBn: "সকাল ৯:০০ - দুপুর ১:০০",
    image: "/doctors/gen1.jpg",
  },
  // Ophthalmology
  {
    id: "d11",
    name: "Dr. Md. Sharfuddin Ahmed",
    nameBn: "ডা. মো. শরফুদ্দিন আহমেদ",
    specialty: "Ophthalmology & Eye Surgery",
    specialtyBn: "চক্ষু বিজ্ঞান ও চোখের সার্জারি",
    department: "ophthalmology",
    hospital: "Ispahani Islamia Eye Institute",
    hospitalBn: "ইস্পাহানি ইসলামিয়া চক্ষু ইনস্টিটিউট",
    location: "Farmgate, Dhaka",
    locationBn: "ফার্মগেট, ঢাকা",
    fee: 800,
    phone: "+880-2-8115533",
    available: "Sun, Tue, Thu",
    availableBn: "রবি, মঙ্গল, বৃহঃ",
    rating: 4.6,
    experience: "20+ years",
    experienceBn: "২০+ বছর",
    chamberTime: "10:00 AM - 2:00 PM",
    chamberTimeBn: "সকাল ১০:০০ - দুপুর ২:০০",
    image: "/doctors/eye1.jpg",
  },
  // Gynecology
  {
    id: "d12",
    name: "Prof. Dr. Rowshan Ara Begum",
    nameBn: "প্রফেসর ডা. রওশন আরা বেগম",
    specialty: "Obstetrics & Gynecology",
    specialtyBn: "প্রসূতি ও স্ত্রীরোগ বিদ্যা",
    department: "gynecology",
    hospital: "Dhaka Medical College Hospital",
    hospitalBn: "ঢাকা মেডিকেল কলেজ হাসপাতাল",
    location: "Secretariat, Dhaka",
    locationBn: "সচিবালয়, ঢাকা",
    fee: 1200,
    phone: "+880-2-55165088",
    available: "Sat, Mon, Wed",
    availableBn: "শনি, সোম, বুধ",
    rating: 4.8,
    experience: "25+ years",
    experienceBn: "২৫+ বছর",
    chamberTime: "4:00 PM - 8:00 PM",
    chamberTimeBn: "বিকাল ৪:০০ - রাত ৮:০০",
    image: "/doctors/gyn1.jpg",
  },
  // Pediatrics
  {
    id: "d13",
    name: "Dr. Md. Kamrul Hasan",
    nameBn: "ডা. মো. কামরুল হাসান",
    specialty: "Pediatrics & Neonatology",
    specialtyBn: "শিশু ও নবজাতক রোগ",
    department: "pediatrics",
    hospital: "Dhaka Shishu Hospital",
    hospitalBn: "ঢাকা শিশু হাসপাতাল",
    location: "Sher-e-Bangla Nagar, Dhaka",
    locationBn: "শের-এ-বাংলা নগর, ঢাকা",
    fee: 800,
    phone: "+880-2-8114310",
    available: "Sun-Thu",
    availableBn: "রবি-বৃহঃ",
    rating: 4.7,
    experience: "18+ years",
    experienceBn: "১৮+ বছর",
    chamberTime: "10:00 AM - 2:00 PM",
    chamberTimeBn: "সকাল ১০:০০ - দুপুর ২:০০",
    image: "/doctors/pedi1.jpg",
  },
  // Urology
  {
    id: "d14",
    name: "Prof. Dr. AKM Khurshidul Alam",
    nameBn: "প্রফেসর ডা. একেএম খুরশিদুল আলম",
    specialty: "Urology & Kidney Transplant",
    specialtyBn: "ইউরোলজি ও কিডনি ট্রান্সপ্লান্ট",
    department: "urology",
    hospital: "Kidney Foundation Hospital",
    hospitalBn: "কিডনি ফাউন্ডেশন হাসপাতাল",
    location: "Mirpur, Dhaka",
    locationBn: "মিরপুর, ঢাকা",
    fee: 1500,
    phone: "+880-2-9002742",
    available: "Sun, Tue, Thu",
    availableBn: "রবি, মঙ্গল, বৃহঃ",
    rating: 4.8,
    experience: "26+ years",
    experienceBn: "২৬+ বছর",
    chamberTime: "5:00 PM - 9:00 PM",
    chamberTimeBn: "বিকাল ৫:০০ - রাত ৯:০০",
    image: "/doctors/uro1.jpg",
  },
  // Psychiatry
  {
    id: "d15",
    name: "Dr. Mekhala Sarkar",
    nameBn: "ডা. মেখলা সরকার",
    specialty: "Psychiatry & Mental Health",
    specialtyBn: "মনোরোগ বিদ্যা ও মানসিক স্বাস্থ্য",
    department: "psychiatry",
    hospital: "National Institute of Mental Health (NIMH)",
    hospitalBn: "জাতীয় মানসিক স্বাস্থ্য ইনস্টিটিউট",
    location: "Sher-e-Bangla Nagar, Dhaka",
    locationBn: "শের-এ-বাংলা নগর, ঢাকা",
    fee: 1000,
    phone: "+880-2-9116551",
    available: "Sat, Mon, Wed",
    availableBn: "শনি, সোম, বুধ",
    rating: 4.6,
    experience: "14+ years",
    experienceBn: "১৪+ বছর",
    chamberTime: "3:00 PM - 7:00 PM",
    chamberTimeBn: "বিকাল ৩:০০ - সন্ধ্যা ৭:০০",
    image: "/doctors/psych1.jpg",
  },
  // Dentistry
  {
    id: "d16",
    name: "Dr. Humayra Musarrat",
    nameBn: "ডা. হুমায়রা মুসাররাত",
    specialty: "Dental & Oral Surgery",
    specialtyBn: "দন্ত ও মুখ সার্জারি",
    department: "dentistry",
    hospital: "Dhaka Dental College Hospital",
    hospitalBn: "ঢাকা ডেন্টাল কলেজ হাসপাতাল",
    location: "Mirpur, Dhaka",
    locationBn: "মিরপুর, ঢাকা",
    fee: 700,
    phone: "+880-2-9003746",
    available: "Sun-Thu",
    availableBn: "রবি-বৃহঃ",
    rating: 4.5,
    experience: "10+ years",
    experienceBn: "১০+ বছর",
    chamberTime: "9:00 AM - 1:00 PM",
    chamberTimeBn: "সকাল ৯:০০ - দুপুর ১:০০",
    image: "/doctors/dent1.jpg",
  },
];

export function findDoctorsByDepartment(department: string): Doctor[] {
  const deptLower = department.toLowerCase().replace(/\s+/g, "_");
  const matched = doctors.filter((d) => {
    const docDept = d.department.toLowerCase();
    return (
      docDept === deptLower ||
      docDept.includes(deptLower) ||
      deptLower.includes(docDept)
    );
  });

  if (matched.length > 0) return matched;

  // Fuzzy matching for common aliases
  const aliases: Record<string, string[]> = {
    cardiology: ["heart", "cardiac", "chest_pain", "cardiovascular"],
    neurology: ["brain", "nerve", "neuro", "headache", "migraine", "stroke", "epilepsy"],
    orthopedics: ["bone", "joint", "fracture", "ortho", "spine", "back_pain"],
    dermatology: ["skin", "derma", "rash", "allergy", "eczema", "acne"],
    gastroenterology: ["stomach", "liver", "gastro", "digestive", "abdomen", "hepatology"],
    ent: ["ear", "nose", "throat", "sinus", "hearing", "tonsil"],
    pulmonology: ["lung", "respiratory", "breathing", "asthma", "chest", "cough"],
    general_medicine: ["general", "medicine", "internal", "fever", "diabetes", "internal_medicine"],
    ophthalmology: ["eye", "vision", "ophthal"],
    gynecology: ["women", "pregnancy", "obstetrics", "gynae", "menstrual"],
    pediatrics: ["child", "baby", "infant", "pediatric", "kid"],
    urology: ["kidney", "urinary", "bladder", "prostate"],
    psychiatry: ["mental", "depression", "anxiety", "psychiatric", "psychology"],
    dentistry: ["tooth", "teeth", "dental", "gum", "oral"],
  };

  for (const [dept, terms] of Object.entries(aliases)) {
    if (terms.some((term) => deptLower.includes(term) || term.includes(deptLower))) {
      return doctors.filter((d) => d.department === dept);
    }
  }

  // Fallback: return general medicine
  return doctors.filter((d) => d.department === "general_medicine");
}
