export type Lang = "en" | "bn";

export const t = {
  en: {
    appName: "NearDoc",
    tagline: "Your AI Health Companion for Dhaka",
    subtitle: "Describe your symptoms — we'll find the right doctor for you",
    inputPlaceholder: "Describe your symptoms... e.g., I have a headache and fever for 3 days",
    voiceBtn: "Hold to speak",
    listening: "Listening...",
    analyzeBtn: "Find My Doctor",
    analyzing: "Analyzing your symptoms...",
    resultsTitle: "Recommended Doctors",
    departmentLabel: "Recommended Department",
    treatmentTitle: "Preliminary Advice",
    doctorName: "Doctor",
    specialty: "Specialty",
    hospital: "Hospital",
    location: "Location",
    fee: "Consultation Fee",
    phone: "Phone",
    available: "Available",
    rating: "Rating",
    disclaimer: "⚠️ This is AI-generated advice for informational purposes only. Always consult a qualified healthcare professional.",
    langToggle: "বাংলা",
    newSearch: "New Search",
    poweredBy: "Powered by AI • Built at Impact Dhaka Hackathon",
    noResults: "No matching doctors found. Please try different symptoms.",
    errorMsg: "Something went wrong. Please try again.",
    symptoms: "Your Symptoms",
    aqiTitle: "Air Quality Index — Dhaka",
    aqiGood: "Good",
    aqiModerate: "Moderate",
    aqiUnhealthy: "Unhealthy for Sensitive Groups",
    aqiVeryUnhealthy: "Very Unhealthy",
    aqiHazardous: "Hazardous",
    aqiAdvice: "Health Advice",
    experience: "Experience",
    chamberTime: "Chamber Hours",
  },
  bn: {
    appName: "NearDoc",
    tagline: "ঢাকার জন্য আপনার AI স্বাস্থ্য সহযোগী",
    subtitle: "আপনার উপসর্গ বর্ণনা করুন — আমরা আপনার জন্য সঠিক ডাক্তার খুঁজে দেব",
    inputPlaceholder: "আপনার উপসর্গ বর্ণনা করুন... যেমন, ৩ দিন ধরে মাথাব্যথা ও জ্বর",
    voiceBtn: "কথা বলতে চাপুন",
    listening: "শুনছি...",
    analyzeBtn: "ডাক্তার খুঁজুন",
    analyzing: "আপনার উপসর্গ বিশ্লেষণ করা হচ্ছে...",
    resultsTitle: "প্রস্তাবিত ডাক্তার",
    departmentLabel: "প্রস্তাবিত বিভাগ",
    treatmentTitle: "প্রাথমিক পরামর্শ",
    doctorName: "ডাক্তার",
    specialty: "বিশেষত্ব",
    hospital: "হাসপাতাল",
    location: "অবস্থান",
    fee: "পরামর্শ ফি",
    phone: "ফোন",
    available: "সময়সূচী",
    rating: "রেটিং",
    disclaimer: "⚠️ এটি শুধুমাত্র তথ্যমূলক উদ্দেশ্যে AI-উৎপন্ন পরামর্শ। সর্বদা একজন যোগ্য স্বাস্থ্যসেবা পেশাদারের সাথে পরামর্শ করুন।",
    langToggle: "English",
    newSearch: "নতুন অনুসন্ধান",
    poweredBy: "AI দ্বারা চালিত • Impact Dhaka হ্যাকাথনে নির্মিত",
    noResults: "মিলে যাওয়া কোনো ডাক্তার পাওয়া যায়নি। অনুগ্রহ করে ভিন্ন উপসর্গ চেষ্টা করুন।",
    errorMsg: "কিছু ভুল হয়েছে। অনুগ্রহ করে আবার চেষ্টা করুন।",
    symptoms: "আপনার উপসর্গ",
    aqiTitle: "বায়ু মানসূচক — ঢাকা",
    aqiGood: "ভালো",
    aqiModerate: "মধ্যম",
    aqiUnhealthy: "সংবেদনশীলদের জন্য অস্বাস্থ্যকর",
    aqiVeryUnhealthy: "খুবই অস্বাস্থ্যকর",
    aqiHazardous: "বিপজ্জনক",
    aqiAdvice: "স্বাস্থ্য পরামর্শ",
    experience: "অভিজ্ঞতা",
    chamberTime: "চেম্বার সময়",
  },
} as const;
